services:
  app:
    image: "oven/bun"
    entrypoint: []
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    ports: ["3000:3000"]
    volumes: ["./:/home/bun/app"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TZ: Asia/Bangkok
    depends_on:
      - db

  db:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Bangkok
    ports:
      - ${POSTGRES_PORT}:5432
    volumes: ["cs321-jmrn-db:/var/lib/postgresql/data"]

volumes:
  cs321-jmrn-db:
